### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by marksteve** [pythonph/pycon-2015-planning#1]
- [x] About
- [x] Past PyCon
  - [x] Pictures
- [x] Call for Speakers
  - [x] Form
- [x] Call for Volunteers
  - [x] Committees
  - [x] Form
- [x] Date and Venue
- [x] Sponsors
  - [x] Packages
  - [x] Form

**Comment by MrValdez** [comment]
# About PyCon Philippines

PyCon Philippines is a volunteer-run, not-for-profit conference centered around the Python Programming language.

The main goal of this conference is to provide a venue where the Python programming language and surrounding technologies can be explored, discussed and exercised.

At the same time an underlying interest would be to gather software engineers, programming enthusiasts, startup founders, corporate IT decision makers, students and IT educators in a 2-day event where they can collaborate and learn from each other.

# About PyCon.Ph 2015

This year, our theme will be "Work and Play with Python". 

Python can be found in the workspace. It has been used to make small scripts to assist the workflow, or to make commercial applications that are sold for profit. Python can be found in play. It has been used to make fun scripts, or even to scratch the artistic curiosity.

This year, we will celebrate the use of Python in work and in play.

# Past PyCon
PyCon 2012 (todo: copy-paste from pycon2014)

PyCon 2014 was held at De La Salle University on February 22-23. It was the second Philippines PyCon and the first PyCon hosted after the establishment (todo: word choice) of Python.Ph.

PyCon 2014 was a huge success with attendees from around the Philippines. PyCon 2014 also paid respect to Malcolm Tredinnick, a PyCon 2012 speaker, who unexpectedly passed away and left a hole in the Python Community. Our keynote speaker, Russell Keith-Magee from Django Software Foundation, shared stories about Malcolm's accomplishments.

PyCon 2014's original website can be found [here](http://pycon-2014.python.ph).

# Call for Speakers

Click here to send us an abstract, a short description and the title of your proposed talk. Your talk should be a maximum of 55 minutes. Try to structure your talk around our theme, "Work and Play with Python".

Please indicate if you are fine with being filmed for our official Python.Ph video repository. 

We will be contacting you before June, a month before PyCon 2015 starts.

# Call for Volunteers

PyCon Philippines is ran by volunteers. The previous PyCon would not have been successful without the help of these individuals. And this year will not be different.

We have many roles that need to be fulfilled to make PyCon Ph 2015 awesome. While all of these roles are hard work, we will be rewarding our volunteers with:
* Free PyCon Ph 2015 tickets
* Free dinner on the first day with the speakers
* Special and limited-run PyCon Ph 2015 Volunteer T-shirt
* PyCon Ph 2015 volunteer's certificate

You can volunteer by clicking on this link.

**Comment by marksteve** [comment]
@MrValdez added Sponsors section

**Comment by MrValdez** [comment]
# Call for Speakers: Presentation or Workshops

Python.Ph is now looking for speakers for our PyCon Philippines 2015 to be held at Ateneo Manila, on July 4-5, 2015.

## Why Participate?
### Rapidly growing Python audience
Python is growing fast in the Philippines. Last year, we had a record of over 200 Pythonistas attend PyCon, ranging from complete beginners to experts. By speaking at PyCon, you can become part of the Python culture.

### A celebration of Python
PyCon is a celebration of the Python language and every year, we gather speakers that will honor and showcase the language.

### Friendly community
Python.Ph have only hosted two PyCon. However, you'll find a friendly core of participants who always seem to return. So we are probably doing something right. These people are also unbelievably nice, as evidenced by all the smiles on our photos.

Our community is so friendly, that passionate and enthusiastic newcomers become even more passionate and enthusiastic with Python that they assimilate into our community. They have started spreading the Python around. 

As a speaker, you will have a chance to talk in front of the charming PyCon participants.

### Driving forward as a Python Pioneer
Speaking to a large audience is hard work. But in exchange, you'll gain reputation amongst your peers as a credible Python speaker.

You will also help establish Python's reputation in the Philippines. Who knows, maybe one of your peers would become surprised that you were one of the pioneers of Python.

### Learning experience
Its not everyday that you will have a chance to speak to over 200 people that came from around the Philippines and the World. You will make mistakes. You will be pressured. BUT you will learn something. And you will learn lessons not only from your presentation, you will also learn from the other speakers.

### Speaker benefits
As a speaker, you will be invited to dinner with other speakers, the PyCon volunteers and the organizers. This will be great time to rest up, network, meet new friends, and most important of all: eat.

## Presentation

Our theme this year is "Work and Play with Python". Your presentation should be structured around this theme.

Click here to send us an abstract, a short description and the title of your proposed talk. Your talk should be a maximum of 55 minutes. 

The deadline for submission of presentations will be on May 31, 2015.

## Workshops

We also hold workshops during PyCon Philippines. We traditionally have two workshops: Beginner Python and Django. Both of these workshops lasts 4 hours.

If you would like to host a workshop, please click here to send us an abstract, level of difficulty and running time for your workshop. We will then contact you for a practice session so we can evaluate your material.

The deadline for submission of workshop proposals will be on May 15, 2015.
