### ISSUE TITLE
In-campus location map

### ISSUE THREAD

**Issue by cr8ivecodesmith** [pythonph/pycon-2015-planning#6]
We want an in-campus location map that points to the registration booth, sponsor booths, conference halls, workshop rooms, restrooms, food, etc.

This will reduce people getting lost.

**Comment by rukku** [comment]
Is there a specific building already? Anybody got a sketch?

**Comment by marksteve** [comment]
@rukku Venue is here: http://pycon.python.ph/date-and-venue.html Want to help out with this? :D

**Comment by rukku** [comment]
@marksteve Sure! What level do we want? Floor plan level?

**Comment by shimofuri** [comment]
@rukku @marksteve I'm in the opinion that we should not post, publicly, a floor plan for security reasons and I think we will need clearance from the host to share that level of detail anyway.  I guess giving people directions to which gate/campus entrance to take should be sufficient. The registration team/ushers can be positioned at the entrances to give directions (printed) to the building/rooms.

Parking details can be made public though and, based from previous experience, is a necessary information.
