### ISSUE TITLE
Reroute ph.pycon.org to pycon.python.ph

### ISSUE THREAD

**Issue by shimofuri** [pythonph/pycon-2015-planning#8]
ph.pycon.org is currently pointing to the 2014 site and must be rerouted to the 2015 site

**Comment by shimofuri** [comment]
If this is rerouted, the "PyCon" link in the lower left corner of the python.ph landing page (current HREF pointing to ph.pycon.org will also correctly route to the 2015 PyCon PH page. Or do we want that current PyCon will always be at pycon.python.ph?

**Comment by marksteve** [comment]
@shimofuri we'll do this once site is ready to be published. thanks for the reminder :D

**Comment by codemickeycode** [comment]
done
